### ISSUE TITLE
Lost scrollbar when reload page with cursor inside Optiscroll area

### ISSUE THREAD

**Issue by brunowego** [wilsonfletcher/Optiscroll#16]
When reload page with cursor inside Optiscroll area the scrollbar not load, but if move cursor outside and back works:

![bug](https://cloud.githubusercontent.com/assets/441774/9733430/8c9ca16a-5601-11e5-8e54-3b97bccff81c.gif)

**Comment by albertogasparin** [comment]
What technique are you using to show/hide the scrollbars? The default CSS only method? 
And are scrollbars correctly created (but not shown) or are they missing from the DOM?

**Comment by brunowego** [comment]
@albertogasparin I only used the normal technique, but with Angular:

```js
angular
  .module('ngScrollbar', [])
  .directive('ngScrollbar', ngScrollbar);

function ngScrollbar() {
  var directive = {
    restrict: 'A',
    transclude: true,
    link: link,
    template: '<div class="scrollbar-content" ng-transclude></div>'
  };

  return directive;

  function link(scope, element) {
    element.addClass('scrollbar');

    var options = {
      forceScrollbars: true,
      classPrefix: 'scrollbar'
    };

    new Optiscroll(element[0], options);
  }
}
```

Below the sass code:

```scss
////
/// Scrollbar
////

$scrollbar-size: .5rem !default;
$scrollbar-radius: .5rem !default;
$scrollbar-space: ($scrollbar-size / 2) !default;

.scrollbar {
  overflow: hidden;
  position: relative;

  // Wrapper
  &-content {
    bottom: 0;
    left: 0;
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    position: absolute;
    right: 0;
    top: 0;
  }

  // Overflow
  &-v,
  &-h {
    -webkit-backface-visibility: hidden;
    background-color: transparent;
    opacity: 0;
    position: absolute;
    transition: opacity .2s ease 0s;
    user-select: none;
  }

  &-v {
    bottom: $scrollbar-space;
    right: 0;
    top: $scrollbar-space;
    width: 0;
  }

  &-h {
    bottom: 0;
    height: 0;
    left: $scrollbar-space;
    right: $scrollbar-space;
  }

  // Track
  &-vtrack,
  &-htrack {
    background-color: rgba(0, 0, 0, .5);
    border-radius: $scrollbar-radius;
    box-sizing: border-box;
    opacity: 0;
    position: absolute;
    transform: translate(0%, 0%);
  }

  &-vtrack {
    right: $scrollbar-space;
    width: $scrollbar-size;
  }

  &-htrack {
    bottom: $scrollbar-space;
    height: $scrollbar-size;
  }

  // On
  &.vtrack-on {
    &:hover > .scrollbar-v {
      opacity: 1;
    }
  }

  &.htrack-on {
    &:hover > .scrollbar-h {
      opacity: 1;
    }
  }
}

// On
.vtrack-on > .scrollbar-v .scrollbar-vtrack {
  opacity: 1;
}

.htrack-on > .scrollbar-h .scrollbar-htrack {
  opacity: 1;
}

// Track
.vtrack-on.htrack-on {
  > .scrollbar-v {
    bottom: $scrollbar-size;
  }

  > .scrollbar-h {
    right: $scrollbar-size;
  }
}
```
